from .base import *  # noqa: F401, F403

DEBUG = False

SIMPLE_JWT["AUTH_COOKIE_SECURE"] = True  # noqa: F405
SIMPLE_JWT["AUTH_COOKIE_SAMESITE"] = "Strict"  # noqa: F405

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
